version: '3.8'

services:
  jira-odoo-sync:
    build: .
    container_name: jira-odoo-connector
    env_file: .env
    volumes:
      - ./logs:/app/logs
    restart: no
    # Default command for one-time execution
    command: python cron_sync.py
